//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVienHunre
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHocPhan()
        {
            this.ThamGiaLopHoc = new HashSet<ThamGiaLopHoc>();
        }
    
        public string maLopHocPhan { get; set; }
        public Nullable<int> namHoc { get; set; }
        public Nullable<int> hocKy { get; set; }
        public string moTa { get; set; }
        public Nullable<double> gioiHanSinhVien { get; set; }
        public int idLopHocPhan { get; set; }
        public Nullable<int> idGiangVien { get; set; }
        public Nullable<int> idMonHoc { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGiaLopHoc> ThamGiaLopHoc { get; set; }
    }
}
