//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVienHunre
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qlsinhvienhunreEntities : DbContext
    {
        public qlsinhvienhunreEntities()
            : base("name=qlsinhvienhunreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiangVien> GiangVien { get; set; }
        public virtual DbSet<HinhThuc> HinhThuc { get; set; }
        public virtual DbSet<Lop> Lop { get; set; }
        public virtual DbSet<LopHocPhan> LopHocPhan { get; set; }
        public virtual DbSet<MonHoc> MonHoc { get; set; }
        public virtual DbSet<NganhHoc> NganhHoc { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<PhanChiaMonHoc> PhanChiaMonHoc { get; set; }
        public virtual DbSet<SinhVien> SinhVien { get; set; }
        public virtual DbSet<ThamGiaLopHoc> ThamGiaLopHoc { get; set; }
    }
}
