//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVienHunre
{
    using System;
    using System.Collections.Generic;
    
    public partial class NganhHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NganhHoc()
        {
            this.Lop = new HashSet<Lop>();
            this.PhanChiaMonHoc = new HashSet<PhanChiaMonHoc>();
        }
    
        public string maNganhHoc { get; set; }
        public string tenNganhHoc { get; set; }
        public Nullable<int> soTinChi { get; set; }
        public Nullable<int> namBatDau { get; set; }
        public int idNganhHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop> Lop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanChiaMonHoc> PhanChiaMonHoc { get; set; }
    }
}
