//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVienHunre
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public string chucVu { get; set; }
        public string matKhau { get; set; }
        public int idNguoiDung { get; set; }
        public Nullable<int> idSinhVien { get; set; }
        public Nullable<int> idGiangVien { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
