//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVienHunre
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanChiaMonHoc
    {
        public int idNganhHoc { get; set; }
        public int idMonHoc { get; set; }
        public int idChiaMon { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual NganhHoc NganhHoc { get; set; }
    }
}
